spring:
    application:
        name: video-service
    data:
      mongodb:
        uri: mongodb://host.docker.internal:27017/test
        database: test
    main:
      allow-bean-definition-overriding: true
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
    redis:
      uri: redis://host.docker.internal:6379


aws:
  accessKey: <accessKey>
  secretKey: <secretKey>
  region: us-east-1
  maxConnections: 100
  connectionTimeOut: 60000

searchServiceUrl: http://host.docker.internal:8000/search
